# Mathematical Foundations of Machine Learning
## Part 1: Linear Algebra

**Target Audience:** Beginners new to Python programming

### Overview
Linear algebra is the foundation of machine learning. All ML data is represented as vectors and matrices. This notebook teaches you:
- Vectors and scalars
- Matrices and datasets
- Vector operations
- Matrix operations
- Norms and distances
- Inverse and determinant

### Why This Matters
Without linear algebra, you cannot:
- Understand how data is represented
- Perform computations on datasets
- Build neural networks
- Make predictions at scale

**The good news:** Linear algebra is geometric and intuitive once you understand it!

## Section 1.1: Vectors and Scalars

**Scalar:** A single number (e.g., 5, -3.2, 0)

**Vector:** An ordered list of numbers representing one data point with multiple features.

### Example
A person can be represented as: [height, weight, age]
- height = 180 cm
- weight = 75 kg  
- age = 30 years

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# === SCALAR ===
# A scalar is just a single number
scalar_value = 5
print("SCALAR (Single Number)")
print("=" * 50)
print(f"Value: {scalar_value}")
print(f"Type: {type(scalar_value).__name__}")
print()

# === VECTOR ===
# A vector is a list of numbers representing ONE data point with multiple features
# Example: Person's attributes [height_cm, weight_kg, age_years]
person_features = np.array([180, 75, 30])
print("VECTOR (List of Numbers - One Data Point)")
print("=" * 50)
print(f"Features: {person_features}")
print(f"Shape: {person_features.shape}")
print(f"Type: {type(person_features).__name__}")
print()

# INTERPRETATION: What does each element represent?
print("INTERPRETATION")
print("=" * 50)
print(f"Element 0 (Height): {person_features[0]} cm")
print(f"Element 1 (Weight): {person_features[1]} kg")
print(f"Element 2 (Age): {person_features[2]} years")
print()
print("KEY INSIGHT: This vector represents ONE PERSON with THREE FEATURES")

In [13]:
# INTERPRETATION: What does each element represent?
print("INTERPRETATION")
print("=" * 900)
print(f"Element 0 (Height): {person_features[0]} cm")
print(f"Element 1 (Weight): {person_features[1]} kg")
print(f"Element 2 (Age): {person_features[2]} years")
print()
print("KEY INSIGHT: This vector represents ONE PERSON with THREE FEATURES")

INTERPRETATION
Element 0 (Height): 180 cm
Element 1 (Weight): 75 kg
Element 2 (Age): 30 years

KEY INSIGHT: This vector represents ONE PERSON with THREE FEATURES


In [5]:
# === VECTOR ===
# A vector is a list of numbers representing ONE data point with multiple features
# Example: Person's attributes [height_cm, weight_kg, age_years]
person_features = np.array([180, 75, 30])
print("VECTOR (List of Numbers - One Data Point)")
print("=" * 50)
print(f"Features: {person_features}")
print(f"Shape: {person_features.shape}")
print(f"Type: {type(person_features).__name__}")
print()

VECTOR (List of Numbers - One Data Point)
Features: [180  75  30]
Shape: (3,)
Type: ndarray



In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# === SCALAR ===
# A scalar is just a single number
scalar_value = 5
print("SCALAR (Single Number)")
print("=" * 50)
print(f"Value: {scalar_value}")
print(f"Type: {type(scalar_value).__name__}")
print()

SCALAR (Single Number)
Value: 5
Type: int



## Section 1.2: Matrices (Datasets)

**Matrix:** A 2D table of numbers (rows × columns)

In machine learning:
- **Each row** = one data point
- **Each column** = one feature

### Example
Dataset with 3 people and 3 features each [height, weight, age]

In [ ]:
# === MATRIX ===
# A matrix is a 2D array - representing MULTIPLE data points with multiple features
# Example dataset: 3 people with 3 attributes each
people_data = np.array([
    [180, 75, 30],      # Person 1: height=180cm, weight=75kg, age=30
    [165, 65, 25],      # Person 2: height=165cm, weight=65kg, age=25
    [175, 70, 35]       # Person 3: height=175cm, weight=70kg, age=35
])

print("MATRIX (Dataset - Multiple Data Points)")
print("=" * 50)
print("Dataset:")
print(people_data)
print()
print(f"Shape: {people_data.shape}")
print(f"Meaning: {people_data.shape[0]} rows (data points), {people_data.shape[1]} columns (features)")
print()

# Accessing specific elements
print("ACCESSING SPECIFIC ELEMENTS")
print("=" * 50)
print(f"people_data[0, 0] = {people_data[0, 0]}  (Person 1's height)")
print(f"people_data[1, 2] = {people_data[1, 2]}  (Person 2's age)")
print(f"people_data[2, 1] = {people_data[2, 1]}  (Person 3's weight)")
print()

# Accessing entire rows and columns
print("ACCESSING ENTIRE ROWS AND COLUMNS")
print("=" * 50)
print(f"Row 0 (Person 1): {people_data[0, :]}")
print(f"Column 0 (All heights): {people_data[:, 0]}")
print()

print("KEY INSIGHT: This is how ALL machine learning data is stored!")
print("Rows = data points (samples), Columns = features (attributes)")

## Section 1.3: Vector Operations

### Common Operations
1. **Addition:** Element-wise addition
2. **Scalar Multiplication:** Multiply each element by a number
3. **Dot Product:** Sum of element-wise products (VERY IMPORTANT!)
4. **Norm:** Magnitude/length of vector

In [ ]:
# Define two vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

print("Original Vectors")
print("=" * 50)
print(f"Vector A: {vector_a}")
print(f"Vector B: {vector_b}")
print()

# 1. Vector Addition
result_add = vector_a + vector_b
print("1. VECTOR ADDITION (A + B)")
print("=" * 50)
print(f"Result: {result_add}")
print(f"Calculation: [{vector_a[0]}+{vector_b[0]}, {vector_a[1]}+{vector_b[1]}, {vector_a[2]}+{vector_b[2]}]")
print(f"           = [{vector_a[0]+vector_b[0]}, {vector_a[1]+vector_b[1]}, {vector_a[2]+vector_b[2]}]")
print()

# 2. Scalar Multiplication
scalar = 2
result_mult = vector_a * scalar
print(f"2. SCALAR MULTIPLICATION (A × {scalar})")
print("=" * 50)
print(f"Result: {result_mult}")
print(f"Calculation: Each element × {scalar}")
print()

# 3. Dot Product (VERY IMPORTANT!)
dot_product = np.dot(vector_a, vector_b)
print("3. DOT PRODUCT (A · B) - MOST IMPORTANT!")
print("=" * 50)
print(f"Result: {dot_product}")
manual_calc = vector_a[0]*vector_b[0] + vector_a[1]*vector_b[1] + vector_a[2]*vector_b[2]
print(f"Calculation:")
print(f"  ({vector_a[0]}×{vector_b[0]}) + ({vector_a[1]}×{vector_b[1]}) + ({vector_a[2]}×{vector_b[2]})")
print(f"  = {vector_a[0]*vector_b[0]} + {vector_a[1]*vector_b[1]} + {vector_a[2]*vector_b[2]}")
print(f"  = {manual_calc}")
print()
print("WHY DOT PRODUCT MATTERS:")
print("  ✓ Measures similarity between vectors")
print("  ✓ Used in linear regression to make predictions")
print("  ✓ Used in neural networks for forward passes")
print("  ✓ Foundation of ALL machine learning computations")

## Section 1.4: Vector Norms (Distance/Magnitude)

**Norm:** A measure of vector magnitude (length)

### Common Norms
- **L2 Norm (Euclidean):** √(x₁² + x₂² + ... + xₙ²) - Most common
- **L1 Norm (Manhattan):** |x₁| + |x₂| + ... + |xₙ|

### Uses
- Calculate distance between data points
- Regularization to prevent overfitting
- Normalize data

In [ ]:
# Example vector
vector = np.array([3, 4])

print("Vector:", vector)
print()

# L2 Norm (Euclidean Distance) - most common
l2_norm = np.linalg.norm(vector, ord=2)
print("L2 NORM (Euclidean Distance) - MOST COMMON")
print("=" * 50)
print(f"Formula: √(x₁² + x₂²)")
print(f"Calculation: √({vector[0]}² + {vector[1]}²)")
print(f"           = √({vector[0]**2} + {vector[1]**2})")
print(f"           = √{vector[0]**2 + vector[1]**2}")
print(f"           = {l2_norm}")
print()

# L1 Norm (Manhattan Distance)
l1_norm = np.linalg.norm(vector, ord=1)
print("L1 NORM (Manhattan Distance)")
print("=" * 50)
print(f"Formula: |x₁| + |x₂|")
print(f"Calculation: |{vector[0]}| + |{vector[1]}|")
print(f"           = {abs(vector[0])} + {abs(vector[1])}")
print(f"           = {l1_norm}")
print()

print("INTERPRETATION")
print("=" * 50)
print(f"  L2 Norm = {l2_norm}")
print(f"  Meaning: Distance from origin (0,0) to point ({vector[0]},{vector[1]}) is {l2_norm} units")
print()
print(f"  L1 Norm = {l1_norm}")
print(f"  Meaning: Manhattan distance (along grid) is {l1_norm} units")
print()
print("HOW IT'S USED IN ML")
print("=" * 50)
print("  • L2: Distance between vectors, regularization (L2 loss)")
print("  • L1: Feature selection, regularization (Lasso)")
print("  • Both: Normalize data before training")

## Section 1.5: Matrix Operations

### Important Matrix Operations
1. **Matrix Addition:** Element-wise addition
2. **Matrix Multiplication:** True matrix multiplication (NOT element-wise!)
3. **Transpose:** Flip rows and columns
4. **Inverse:** Find matrix that when multiplied gives identity
5. **Determinant:** Scalar value indicating matrix invertibility

In [3]:
# Define two matrices
matrix_A = np.array([
    [1, 2],
    [3, 4]
])

matrix_B = np.array([
    [5, 6],
    [7, 8]
])

print("Original Matrices")
print("=" * 50)
print("Matrix A:")
print(matrix_A)
print("\nMatrix B:")
print(matrix_B)
print()

# 1. Matrix Addition
result_add = matrix_A + matrix_B
print("1. MATRIX ADDITION (A + B)")
print("=" * 50)
print(result_add)
print()

# 2. Matrix Multiplication
result_mult = np.dot(matrix_A, matrix_B)
print("2. MATRIX MULTIPLICATION (A @ B) - NOT Element-wise!")
print("=" * 50)
print(f"Formula: Each element [i,j] = sum of (A[i,k] × B[k,j])")
print(result_mult)
print()
print("Step-by-step calculation:")
print(f"  [0,0] = (1×5) + (2×7) = {1*5} + {2*7} = {result_mult[0,0]}")
print(f"  [0,1] = (1×6) + (2×8) = {1*6} + {2*8} = {result_mult[0,1]}")
print(f"  [1,0] = (3×5) + (4×7) = {3*5} + {4*7} = {result_mult[1,0]}")
print(f"  [1,1] = (3×6) + (4×8) = {3*6} + {4*8} = {result_mult[1,1]}")
print()

# 3. Matrix Transpose
result_transpose = matrix_A.T
print("3. MATRIX TRANSPOSE (Flip rows and columns)")
print("=" * 50)
print(f"Original shape: {matrix_A.shape}")
print("Original A:")
print(matrix_A)
print(f"\nTransposed shape: {result_transpose.shape}")
print("Transposed A:")
print(result_transpose)
print()

print("WHY MATRIX OPERATIONS MATTER")
print("=" * 50)
print("  • Matrix multiplication: Apply learned parameters to data")
print("  • Transpose: Rearrange data for computations")
print("  • Used in EVERY machine learning algorithm")

Original Matrices
Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

1. MATRIX ADDITION (A + B)
[[ 6  8]
 [10 12]]

2. MATRIX MULTIPLICATION (A @ B) - NOT Element-wise!
Formula: Each element [i,j] = sum of (A[i,k] × B[k,j])
[[19 22]
 [43 50]]

Step-by-step calculation:
  [0,0] = (1×5) + (2×7) = 5 + 14 = 19
  [0,1] = (1×6) + (2×8) = 6 + 16 = 22
  [1,0] = (3×5) + (4×7) = 15 + 28 = 43
  [1,1] = (3×6) + (4×8) = 18 + 32 = 50

3. MATRIX TRANSPOSE (Flip rows and columns)
Original shape: (2, 2)
Original A:
[[1 2]
 [3 4]]

Transposed shape: (2, 2)
Transposed A:
[[1 3]
 [2 4]]

WHY MATRIX OPERATIONS MATTER
  • Matrix multiplication: Apply learned parameters to data
  • Transpose: Rearrange data for computations
  • Used in EVERY machine learning algorithm


## Section 1.6: Matrix Inverse and Determinant

### Determinant
A scalar value that indicates:
- Whether matrix is invertible (det ≠ 0)
- Volume scaling of matrix transformation

### Inverse
The matrix that, when multiplied by original, gives identity matrix:
A × A⁻¹ = I

### Uses
- Solving linear systems: Ax = b → x = A⁻¹b
- Linear regression: Solving normal equation
- Computing model parameters

In [ ]:
# Example matrix
matrix = np.array([
    [4, 7],
    [2, 6]
])

print("Matrix:")
print(matrix)
print()

# 1. Determinant
det = np.linalg.det(matrix)
print("1. DETERMINANT")
print("=" * 50)
print(f"For 2×2 matrix [[a,b],[c,d]]: det = (a×d) - (b×c)")
print(f"Calculation: (4×6) - (7×2) = {4*6} - {7*2} = {det}")
print()

# 2. Inverse (only if determinant ≠ 0)
if abs(det) > 1e-10:  # Check if non-zero (accounting for floating point errors)
    matrix_inverse = np.linalg.inv(matrix)
    print("2. INVERSE (A⁻¹)")
    print("=" * 50)
    print("The inverse is the matrix that when multiplied by original gives identity:")
    print(matrix_inverse)
    print()

    # Verify: A × A⁻¹ should equal Identity matrix
    identity = np.dot(matrix, matrix_inverse)
    print("3. VERIFICATION: A × A⁻¹ = Identity Matrix")
    print("=" * 50)
    print(np.round(identity, decimals=10))
    print()
    print("INTERPRETATION")
    print("=" * 50)
    print("  Identity matrix has 1s on diagonal, 0s elsewhere")
    print("  This verifies that our inverse is correct!")
else:
    print("2. INVERSE")
    print("=" * 50)
    print("Cannot compute - determinant is 0 (matrix is singular)")
    print()

print()
print("WHY INVERSE IS IMPORTANT IN ML")
print("=" * 50)
print("  • Linear Regression: Solve X @ β = y for β")
print("  • Solution: β = (X^T @ X)^(-1) @ X^T @ y")
print("  • Used to compute optimal model parameters")

## Section 1.7: Practical Application - Feature Scaling

One of the most important uses of linear algebra in ML is **feature normalization**.

### Why?
Features with different scales can make learning harder. Example:
- Age: 20-80 (small range)
- Income: 20000-200000 (large range)

Without scaling, income dominates the model!

In [ ]:
# Example: Different scale features
ages = np.array([25, 30, 45, 50, 35])
incomes = np.array([30000, 45000, 75000, 80000, 55000])

print("ORIGINAL DATA WITH DIFFERENT SCALES")
print("=" * 50)
print(f"Ages: {ages}")
print(f"  Mean: {np.mean(ages):.2f}, Std Dev: {np.std(ages):.2f}")
print()
print(f"Incomes: {incomes}")
print(f"  Mean: {np.mean(incomes):.2f}, Std Dev: {np.std(incomes):.2f}")
print()
print("PROBLEM: Income varies much more than age!")
print("This causes algorithms to focus on income and ignore age.")
print()

# Standardization using z-score normalization
ages_normalized = (ages - np.mean(ages)) / np.std(ages)
incomes_normalized = (incomes - np.mean(incomes)) / np.std(incomes)

print("AFTER STANDARDIZATION (Z-score normalization)")
print("=" * 50)
print(f"Formula: (x - mean) / std_dev")
print()
print(f"Normalized ages: {np.round(ages_normalized, 2)}")
print(f"  Mean: {np.mean(ages_normalized):.2f}, Std Dev: {np.std(ages_normalized):.2f}")
print()
print(f"Normalized incomes: {np.round(incomes_normalized, 2)}")
print(f"  Mean: {np.mean(incomes_normalized):.2f}, Std Dev: {np.std(incomes_normalized):.2f}")
print()
print("RESULT: Both features now have mean≈0 and std≈1")
print("The algorithm treats them fairly!")

## Summary: Linear Algebra in Machine Learning

### Key Concepts
| Concept | What It Is | ML Application |
|---------|-----------|----------------|
| Scalar | Single number | Single value |
| Vector | List of numbers | One data point |
| Matrix | 2D table | Dataset (multiple points) |
| Dot Product | Sum of products | Predictions, similarity |
| Norm | Vector magnitude | Distance, normalization |
| Transpose | Flip rows/cols | Data rearrangement |
| Inverse | Special matrix | Solving equations, regression |

### Key Takeaways
✓ All ML data is vectors and matrices  
✓ Dot product computes predictions  
✓ Matrix multiplication applies transformations  
✓ Norms measure distances  
✓ Inverse solves linear systems  
✓ Understanding these enables understanding all ML!

### Next Steps
- Practice with your own data
- Build intuition through visualization
- Move on to Part 2: Statistics